// Copyright (c) 2025-2026 Maunting Studios
// Licensed under the Business Source License 1.1 - see LICENSE
/**
 * @fileoverview Controlled category icon registry.
 *
 * Category icon values are stored as stable IDs. Legacy emoji values are mapped
 * to these IDs for display only; no arbitrary SVG, HTML, or remote asset is
 * rendered.
 */

import {
  Archive,
  AlarmClock,
  Ambulance,
  Anchor,
  Armchair,
  Atom,
  Baby,
  Badge,
  BadgeCheck,
  Banknote,
  Bell,
  Bike,
  BookMarked,
  BookOpen,
  Bookmark,
  Boxes,
  Briefcase,
  Bug,
  Building2,
  Bus,
  Cable,
  Calendar,
  Camera,
  Car,
  ChartColumn,
  ChartNoAxesColumn,
  CircleDollarSign,
  Cloud,
  Code2,
  ClipboardList,
  CreditCard,
  Cpu,
  Crown,
  Database,
  DoorOpen,
  Dumbbell,
  Earth,
  FileArchive,
  FileCode2,
  FileKey2,
  FileLock2,
  FileSpreadsheet,
  Folder,
  Fingerprint,
  Flame,
  Gamepad2,
  Gem,
  Gift,
  Globe2,
  GraduationCap,
  Hammer,
  HandCoins,
  HardDrive,
  Headphones,
  HeartPulse,
  Home,
  HousePlug,
  IdCard,
  KeyRound,
  Landmark,
  Languages,
  Laptop,
  Layers,
  LifeBuoy,
  Lightbulb,
  LockKeyhole,
  Mail,
  Map,
  Megaphone,
  MonitorSmartphone,
  Music2,
  Network,
  NotebookText,
  Package,
  Palette,
  PenTool,
  Plane,
  Printer,
  Receipt,
  Rocket,
  Route,
  Satellite,
  Scale,
  ScanFace,
  School,
  Search,
  Server,
  Settings2,
  Share2,
  Shield,
  ShieldCheck,
  Ship,
  ShoppingBag,
  Smartphone,
  Sparkles,
  SquareTerminal,
  Star,
  Store,
  TabletSmartphone,
  Tags,
  Terminal,
  Ticket,
  Timer,
  Truck,
  Tv,
  Umbrella,
  University,
  UserCheck,
  UserCog,
  Users,
  WalletCards,
  Wifi,
  Workflow,
  Wrench,
  type LucideIcon,
} from 'lucide-react';

export interface CategoryIconDefinition {
  id: string;
  label: string;
  group: string;
  Icon: LucideIcon;
}

export const CATEGORY_ICON_REGISTRY: Record<string, CategoryIconDefinition> = {
  passwords: { id: 'passwords', label: 'Passwoerter', group: 'security', Icon: LockKeyhole },
  notes: { id: 'notes', label: 'Notizen', group: 'documents', Icon: NotebookText },
  favorites: { id: 'favorites', label: 'Favoriten', group: 'general', Icon: Star },
  platform: { id: 'platform', label: 'Plattform-Accounts', group: 'accounts', Icon: Badge },
  server: { id: 'server', label: 'Server-Accounts', group: 'infrastructure', Icon: Server },
  finance: { id: 'finance', label: 'Finanzen', group: 'finance', Icon: Banknote },
  work: { id: 'work', label: 'Arbeit', group: 'life', Icon: Briefcase },
  private: { id: 'private', label: 'Privat', group: 'life', Icon: Home },
  development: { id: 'development', label: 'Entwicklung', group: 'technology', Icon: Code2 },
  infrastructure: { id: 'infrastructure', label: 'Infrastruktur', group: 'technology', Icon: Network },
  cloud: { id: 'cloud', label: 'Cloud', group: 'technology', Icon: Cloud },
  database: { id: 'database', label: 'Datenbank', group: 'technology', Icon: Database },
  recovery: { id: 'recovery', label: 'Recovery', group: 'security', Icon: Archive },
  authenticator: { id: 'authenticator', label: 'Authenticator', group: 'security', Icon: Smartphone },
  security: { id: 'security', label: 'Sicherheit', group: 'security', Icon: Shield },
  identity: { id: 'identity', label: 'Identitaet', group: 'accounts', Icon: IdCard },
  shopping: { id: 'shopping', label: 'Shopping', group: 'commerce', Icon: ShoppingBag },
  social: { id: 'social', label: 'Social', group: 'accounts', Icon: Users },
  media: { id: 'media', label: 'Medien', group: 'media', Icon: Tv },
  travel: { id: 'travel', label: 'Reisen', group: 'life', Icon: Plane },
  health: { id: 'health', label: 'Gesundheit', group: 'life', Icon: HeartPulse },
  education: { id: 'education', label: 'Bildung', group: 'life', Icon: GraduationCap },
  family: { id: 'family', label: 'Familie', group: 'life', Icon: Users },
  admin: { id: 'admin', label: 'Admin', group: 'system', Icon: Wrench },
  api: { id: 'api', label: 'API', group: 'technology', Icon: KeyRound },
  backup: { id: 'backup', label: 'Backup', group: 'system', Icon: HardDrive },
  keys: { id: 'keys', label: 'Schluessel', group: 'security', Icon: KeyRound },
  devices: { id: 'devices', label: 'Geraete', group: 'technology', Icon: Laptop },
  network: { id: 'network', label: 'Netzwerk', group: 'technology', Icon: Network },
  mail: { id: 'mail', label: 'E-Mail', group: 'accounts', Icon: Mail },
  documents: { id: 'documents', label: 'Dokumente', group: 'documents', Icon: BookOpen },
  gaming: { id: 'gaming', label: 'Gaming', group: 'media', Icon: Gamepad2 },
  music: { id: 'music', label: 'Musik', group: 'media', Icon: Music2 },
  vehicles: { id: 'vehicles', label: 'Fahrzeuge', group: 'life', Icon: Car },
  locations: { id: 'locations', label: 'Orte', group: 'life', Icon: Map },
  tags: { id: 'tags', label: 'Tags', group: 'general', Icon: Tags },
  banking: { id: 'banking', label: 'Banking', group: 'finance', Icon: Landmark },
  payments: { id: 'payments', label: 'Zahlungen', group: 'finance', Icon: WalletCards },
  invoices: { id: 'invoices', label: 'Rechnungen', group: 'finance', Icon: Receipt },
  taxes: { id: 'taxes', label: 'Steuern', group: 'finance', Icon: ChartColumn },
  investments: { id: 'investments', label: 'Investments', group: 'finance', Icon: CircleDollarSign },
  crypto: { id: 'crypto', label: 'Crypto', group: 'finance', Icon: Gem },
  insurance: { id: 'insurance', label: 'Versicherung', group: 'finance', Icon: ShieldCheck },
  payroll: { id: 'payroll', label: 'Gehalt', group: 'finance', Icon: HandCoins },
  contracts: { id: 'contracts', label: 'Vertraege', group: 'documents', Icon: FileLock2 },
  certificates: { id: 'certificates', label: 'Zertifikate', group: 'documents', Icon: BadgeCheck },
  spreadsheets: { id: 'spreadsheets', label: 'Tabellen', group: 'documents', Icon: FileSpreadsheet },
  archive: { id: 'archive', label: 'Archiv', group: 'documents', Icon: FileArchive },
  bookmarks: { id: 'bookmarks', label: 'Lesezeichen', group: 'documents', Icon: Bookmark },
  research: { id: 'research', label: 'Recherche', group: 'documents', Icon: Search },
  code: { id: 'code', label: 'Code', group: 'technology', Icon: FileCode2 },
  terminal: { id: 'terminal', label: 'Terminal', group: 'technology', Icon: Terminal },
  shell: { id: 'shell', label: 'Shell', group: 'technology', Icon: SquareTerminal },
  hardware: { id: 'hardware', label: 'Hardware', group: 'technology', Icon: Cpu },
  wifi: { id: 'wifi', label: 'WLAN', group: 'technology', Icon: Wifi },
  nas: { id: 'nas', label: 'NAS', group: 'technology', Icon: Boxes },
  router: { id: 'router', label: 'Router', group: 'technology', Icon: Cable },
  smartHome: { id: 'smartHome', label: 'Smart Home', group: 'technology', Icon: HousePlug },
  mobile: { id: 'mobile', label: 'Mobile', group: 'technology', Icon: TabletSmartphone },
  integrations: { id: 'integrations', label: 'Integrationen', group: 'technology', Icon: Workflow },
  ai: { id: 'ai', label: 'KI', group: 'technology', Icon: Sparkles },
  bugBounty: { id: 'bugBounty', label: 'Bug Bounty', group: 'security', Icon: Bug },
  passkeys: { id: 'passkeys', label: 'Passkeys', group: 'security', Icon: Fingerprint },
  vaults: { id: 'vaults', label: 'Vaults', group: 'security', Icon: FileKey2 },
  emergency: { id: 'emergency', label: 'Notfall', group: 'security', Icon: LifeBuoy },
  permissions: { id: 'permissions', label: 'Rechte', group: 'security', Icon: UserCheck },
  access: { id: 'access', label: 'Zugriff', group: 'security', Icon: DoorOpen },
  alerts: { id: 'alerts', label: 'Warnungen', group: 'security', Icon: Bell },
  enterprise: { id: 'enterprise', label: 'Unternehmen', group: 'work', Icon: Building2 },
  clients: { id: 'clients', label: 'Kunden', group: 'work', Icon: Users },
  projects: { id: 'projects', label: 'Projekte', group: 'work', Icon: Layers },
  tasks: { id: 'tasks', label: 'Aufgaben', group: 'work', Icon: ClipboardList },
  meetings: { id: 'meetings', label: 'Meetings', group: 'work', Icon: Calendar },
  design: { id: 'design', label: 'Design', group: 'work', Icon: Palette },
  marketing: { id: 'marketing', label: 'Marketing', group: 'work', Icon: Megaphone },
  legal: { id: 'legal', label: 'Rechtliches', group: 'work', Icon: Scale },
  tools: { id: 'tools', label: 'Tools', group: 'work', Icon: Hammer },
  ecommerce: { id: 'ecommerce', label: 'E-Commerce', group: 'commerce', Icon: Store },
  delivery: { id: 'delivery', label: 'Lieferung', group: 'commerce', Icon: Truck },
  coupons: { id: 'coupons', label: 'Coupons', group: 'commerce', Icon: Ticket },
  gifts: { id: 'gifts', label: 'Geschenke', group: 'commerce', Icon: Gift },
  photos: { id: 'photos', label: 'Fotos', group: 'media', Icon: Camera },
  streaming: { id: 'streaming', label: 'Streaming', group: 'media', Icon: Tv },
  podcasts: { id: 'podcasts', label: 'Podcasts', group: 'media', Icon: Headphones },
  news: { id: 'news', label: 'News', group: 'media', Icon: BookMarked },
  gamingOnline: { id: 'gamingOnline', label: 'Online Gaming', group: 'media', Icon: Gamepad2 },
  flight: { id: 'flight', label: 'Flug', group: 'travel', Icon: Plane },
  hotel: { id: 'hotel', label: 'Hotel', group: 'travel', Icon: Building2 },
  transport: { id: 'transport', label: 'Transport', group: 'travel', Icon: Bus },
  routes: { id: 'routes', label: 'Routen', group: 'travel', Icon: Route },
  shipping: { id: 'shipping', label: 'Schiff', group: 'travel', Icon: Ship },
  outdoors: { id: 'outdoors', label: 'Outdoor', group: 'travel', Icon: Umbrella },
  fitness: { id: 'fitness', label: 'Fitness', group: 'health', Icon: Dumbbell },
  doctor: { id: 'doctor', label: 'Arzt', group: 'health', Icon: Ambulance },
  pharmacy: { id: 'pharmacy', label: 'Apotheke', group: 'health', Icon: HeartPulse },
  school: { id: 'school', label: 'Schule', group: 'education', Icon: School },
  university: { id: 'university', label: 'Universitaet', group: 'education', Icon: University },
  languages: { id: 'languages', label: 'Sprachen', group: 'education', Icon: Languages },
  kids: { id: 'kids', label: 'Kinder', group: 'family', Icon: Baby },
  household: { id: 'household', label: 'Haushalt', group: 'life', Icon: Armchair },
  utilities: { id: 'utilities', label: 'Versorger', group: 'life', Icon: Lightbulb },
  vehicleService: { id: 'vehicleService', label: 'Fahrzeugservice', group: 'life', Icon: Wrench },
  timeline: { id: 'timeline', label: 'Termine', group: 'life', Icon: AlarmClock },
  publicServices: { id: 'publicServices', label: 'Behoerden', group: 'life', Icon: Landmark },
  global: { id: 'global', label: 'Global', group: 'general', Icon: Earth },
  launch: { id: 'launch', label: 'Launch', group: 'general', Icon: Rocket },
  shared: { id: 'shared', label: 'Geteilt', group: 'general', Icon: Share2 },
  settings: { id: 'settings', label: 'Einstellungen', group: 'system', Icon: Settings2 },
  monitoring: { id: 'monitoring', label: 'Monitoring', group: 'system', Icon: ChartNoAxesColumn },
  satellite: { id: 'satellite', label: 'Satellit', group: 'system', Icon: Satellite },
  anchor: { id: 'anchor', label: 'Anker', group: 'general', Icon: Anchor },
  generic: { id: 'generic', label: 'Kategorie', group: 'general', Icon: Folder },
};

export const CATEGORY_ICON_PRESET_IDS = Object.keys(CATEGORY_ICON_REGISTRY)
  .filter((id) => id !== 'generic');

export const LEGACY_CATEGORY_EMOJI_MAP: Record<string, string> = {
  '\u{1F4C1}': 'generic',
  '\u{1F4BC}': 'work',
  '\u{1F3E0}': 'private',
  '\u{1F4B3}': 'finance',
  '\u{1F6D2}': 'shopping',
  '\u{1F3AE}': 'gaming',
  '\u{2708}\u{FE0F}': 'travel',
  '\u{2764}\u{FE0F}': 'health',
  '\u{1F510}': 'security',
  '\u{1F3E6}': 'finance',
  '\u{1F4E7}': 'mail',
  '\u{1F4F1}': 'devices',
  '\u{1F4BB}': 'development',
  '\u{1F9F0}': 'admin',
  '\u{1F4DA}': 'education',
  '\u{1F3AC}': 'media',
  '\u{1F3B5}': 'music',
  '\u{1F3E5}': 'health',
  '\u{1F697}': 'vehicles',
  '\u{1F381}': 'shopping',
  '\u{2601}\u{FE0F}': 'cloud',
  '\u{1F9FE}': 'documents',
  '\u{1F3F7}\u{FE0F}': 'tags',
  '\u{2B50}': 'favorites',
};

export function getCategoryIconDefinition(id: string | null | undefined): CategoryIconDefinition {
  return CATEGORY_ICON_REGISTRY[id ?? 'generic'] ?? CATEGORY_ICON_REGISTRY.generic;
}
