const sharp = require('sharp');
const path = require('path');
const fs = require('fs');
const { execFileSync, execSync } = require('child_process');

const root = path.join(__dirname, '..');
const src = path.join(root, 'public', 'singra-icon.png');
const pub = path.join(__dirname, '..', 'public');
const tauriIcons = path.join(root, 'src-tauri', 'icons');
const cornerRadiusRatio = 0.22;

function createRoundedRectMask(size, radius) {
  return Buffer.from(`
    <svg width="${size}" height="${size}" viewBox="0 0 ${size} ${size}" xmlns="http://www.w3.org/2000/svg">
      <rect x="0" y="0" width="${size}" height="${size}" rx="${radius}" ry="${radius}" fill="#fff" />
    </svg>
  `);
}

async function createRoundedIconBuffer(inputBuffer, size) {
  const radius = Math.round(size * cornerRadiusRatio);
  const mask = createRoundedRectMask(size, radius);
  return sharp(inputBuffer)
    .resize(size, size, { fit: 'cover' })
    .composite([{ input: mask, blend: 'dest-in' }])
    .png()
    .toBuffer();
}

async function run() {
  const sourceBuffer = fs.readFileSync(src);
  const source = sharp(sourceBuffer);
  const metadata = await source.metadata();
  if (metadata.width !== metadata.height) {
    throw new Error(`Icon source must be square, got ${metadata.width}x${metadata.height}`);
  }

  const roundedMaster = await createRoundedIconBuffer(sourceBuffer, metadata.width);
  fs.writeFileSync(src, roundedMaster);

  // PWA icons
  await fs.promises.writeFile(path.join(pub, 'pwa-192.png'), await createRoundedIconBuffer(sourceBuffer, 192));
  await fs.promises.writeFile(path.join(pub, 'pwa-512.png'), await createRoundedIconBuffer(sourceBuffer, 512));
  await fs.promises.writeFile(path.join(pub, 'apple-touch-icon.png'), await createRoundedIconBuffer(sourceBuffer, 180));

  // Maskable icons (20% padding, dark background matching --background)
  const bg = { r: 11, g: 18, b: 32, alpha: 1 };

  const inner192 = Math.round(192 * 0.8);
  const pad192 = Math.round((192 - inner192) / 2);
  const buf192 = await createRoundedIconBuffer(sourceBuffer, inner192);
  await sharp({ create: { width: 192, height: 192, channels: 4, background: bg } })
    .composite([{ input: buf192, left: pad192, top: pad192 }])
    .png().toFile(path.join(pub, 'pwa-192-maskable.png'));

  const inner512 = Math.round(512 * 0.8);
  const pad512 = Math.round((512 - inner512) / 2);
  const buf512 = await createRoundedIconBuffer(sourceBuffer, inner512);
  await sharp({ create: { width: 512, height: 512, channels: 4, background: bg } })
    .composite([{ input: buf512, left: pad512, top: pad512 }])
    .png().toFile(path.join(pub, 'pwa-512-maskable.png'));

  // Desktop/mobile app icons. Tauri generates .ico, .icns, Windows Store,
  // Android and iOS sizes from the same high-resolution source.
  const tauriBin = path.join(root, 'node_modules', '.bin', process.platform === 'win32' ? 'tauri.cmd' : 'tauri');
  if (process.platform === 'win32') {
    const quote = (value) => `"${String(value).replace(/"/g, '""')}"`;
    execSync(`${quote(tauriBin)} icon ${quote(src)} --output ${quote(tauriIcons)}`, {
      cwd: root,
      stdio: 'inherit',
    });
  } else {
    execFileSync(tauriBin, ['icon', src, '--output', tauriIcons], {
      cwd: root,
      stdio: 'inherit',
    });
  }

  // Use the real multi-size ICO generated by Tauri for the web favicon too.
  fs.copyFileSync(path.join(tauriIcons, 'icon.ico'), path.join(pub, 'favicon.ico'));

  console.log('All icons generated successfully!');
}

run().catch(e => { console.error(e); process.exit(1); });
