// Copyright (c) 2025-2026 Maunting Studios
// Licensed under the Business Source License 1.1 — see LICENSE
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { LockFunc } from '@supabase/auth-js';
import type { Database } from './types';
import { runtimeConfig } from '@/config/runtimeConfig';

const SUPABASE_URL = runtimeConfig.supabaseUrl;
const SUPABASE_PUBLISHABLE_KEY = runtimeConfig.supabasePublishableKey;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

const memoryStore = new Map<string, string>();

const inMemoryStorage = {
  getItem: (key: string) => memoryStore.get(key) || null,
  setItem: (key: string, value: string) => { memoryStore.set(key, value); },
  removeItem: (key: string) => { memoryStore.delete(key); },
};

// The storage above is local to one WebView process, so cross-tab Web Locks are
// unnecessary and can abort OAuth callbacks in Tauri.
const inMemoryAuthLock: LockFunc = async (_name, _acquireTimeout, fn) => await fn();

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: inMemoryStorage,
    persistSession: true,
    autoRefreshToken: false,
    detectSessionInUrl: true,
    lock: inMemoryAuthLock,
  }
});
