// Copyright (c) 2025-2026 Maunting Studios
// Licensed under the Business Source License 1.1 — see LICENSE
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { runtimeConfig } from '@/config/runtimeConfig';

const SUPABASE_URL = runtimeConfig.supabaseUrl;
const SUPABASE_PUBLISHABLE_KEY = runtimeConfig.supabasePublishableKey;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

const inMemoryStorage = {
  getItem: () => null,
  setItem: () => { },
  removeItem: () => { },
};

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: inMemoryStorage,
    persistSession: false,
    autoRefreshToken: false,
    detectSessionInUrl: true,
  }
});
